---
title: "Orycotolagus Cuniculus"
author: "Anita Dhillon"
date: "2023-05-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
```




# Oryctolagus Cuniculus

## Background Info

Data Set Title: Previous exposure to myxomatos reduces survival of European Rabbits during Outbreak of Haemorrhagic disease 

Author: Barnett,Louise

Publication Date: May 18,2019

Link to Data Set: 
https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.j91d66c


Article Title: Previous exposure to myxomatosis reduces survival of European Rabbits during Outbreak of Hemorrhagic disease
 
Article Publication Date: May 26, 2018

Link to Article: https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2664.13187


Summary: In Australia, two viruses were introduced to the species (Oryctolagus cuniculus) to control the population. It was seen that there was a brief decline, although it continues to affect the population, rabbits still remain an issue. 

Experimental Method: 18 year old antibody assay data was used to test whether the two diseases (myxoma and hemorrhagic) will affect the survival of individual wild rabbits.

Results: Rabbit Hemorrhagic was seen to reduce the survival of the individuals with no immunity. This was compared to the myxomatosis outbreaks that had a smaller effect and it was also seen that the myxomatosis outbreaks were seen to span more than twice as many trips. It was also seen that the biological control agents had a large impact on the population. The rabbits that were both introduced to the myxomatosis virus and rabbit hemorrhagic disease resulted in a lower survival rate compared to the the rabbits not exposed to either. 















## About me

Hello ! Welcome to my website! My name is Anita Dhillon, I am a 3rd year Biology student here at UCM. I am taking this course to further increase my knowledge of R studio and learn more about the Open Tree of Life. I am a premed student and graduate this term which I am super excited about! I extremely enjoyed taking this class with Luna and learned alot! Thank you for a great semester :)). 













